# Generated by Django 3.1.2 on 2020-11-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='discriptin',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='ram',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='rom',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
