# Generated by Django 3.1.2 on 2020-11-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20201115_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='discriptin',
            new_name='discription',
        ),
    ]
