# Generated by Django 3.1.2 on 2020-11-07 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20201108_0427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
