# Generated by Django 3.1.2 on 2020-11-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0003_delete_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=40)),
                ('supplier_address', models.CharField(max_length=50)),
                ('supplier_phone', models.CharField(max_length=12)),
                ('gst_uin', models.CharField(max_length=30)),
                ('state_name', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('brand_name', models.CharField(max_length=20)),
            ],
        ),
    ]
