# Generated by Django 3.1.2 on 2020-11-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_address',
            field=models.CharField(max_length=200),
        ),
    ]
