# Generated by Django 3.1.2 on 2020-11-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_productmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=60)),
                ('ram', models.CharField(max_length=40)),
                ('rom', models.CharField(max_length=60)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.supplier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.productmodel')),
            ],
        ),
    ]
